version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lamj1gdh5d3y"
s3_prefix = "app-backend"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = false
parameter_overrides = "stage=\"development\" backupRegion=\"us-west-2\" enablePersistentStorage=\"true\" enableAWSAuth=\"true\" enableBackup=\"false\" dbTableName=\"DBTable\" appId=\"t52x7zk6ls6p\" enableS3Replication=\"false\" enableVPC=\"false\" enableSecurity=\"true\" enableOpenSearch=\"false\" enableApiCDN=\"false\" corsAllowedOrigins=\"*\" emailDistributionSubscription=\"ianballard.dev@gmail.com\""
