version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-backend-secondary"
s3_prefix = "app-backend-secondary"
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = false
parameter_overrides = "stage=\"development\" replicaRegion=\"us-east-2\" enablePersistentStorage=\"true\" enableAWSAuth=\"true\" enableBackup=\"false\" dbTableName=\"DBTable\" enableSecurity=\"true\" enableS3Replication=\"false\" enableVPC=\"false\" enableOpenSearch=\"false\" enableApiCDN=\"false\" corsAllowedOrigins=\"*\""

