version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "us-west-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = false
resolve_s3 = true
disable_rollback = false
