version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app-backend"
s3_prefix = "app-backend"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "stage=\"development\" replicaRegion=\"us-west-2\" appId=\"t52x7zk6ls6p\" dbTableName=\"DBTable\" stackType=\"primary\" enablePersistentStorage=\"true\" enableVPC=\"false\" enableOpenSearch=\"false\" enableS3Replication=\"false\" enableAWSAuth=\"true\" enableBackup=\"false\" enableSecurity=\"false\" corsAllowedOrigins=\"*\" emailDistributionSubscription=\"ianballard.dev@gmail.com\" hostedZoneName=\"ianballard.net\" enableDNS=\"true\" hostedZoneId=\"Z05462233VILWAA1DI0O6\""
resolve_s3 = true
disable_rollback = false
confirm_changeset = false
