AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DB Event Stack

Parameters:
  stage:
    Description: "Stage"
    Type: String
  backupRegion:
    Description: "Backup Region"
    Type: String
  coreLayer:
    Description: "Core Library Layer"
    Type: String
  dbStreamArn:
    Description: "DB Stream ARN"
    Type: String
  securityGroup:
    Description: "Lambda VPC security group"
    Type: String
    Default: ""
  vpcSubnetIds:
    Description: "Lambda VPC Subnets"
    Type: CommaDelimitedList
    Default: ""
  enableVPC:
    Description: "Is VPC enabled (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  enableOpenSearch:
    Description: "Enable Open Search (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'

Conditions:
  isVPCEnabled: !Equals [ !Ref enableVPC, 'true' ]

Globals:
  Function:
    MemorySize: 256
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        "stage": !Ref "stage"
        "region": !Ref AWS::Region
        "SEARCH_ENABLED": !Ref enableOpenSearch
    Layers:
      - !Ref coreLayer
    VpcConfig: !If
      - isVPCEnabled
      - SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds: !Ref vpcSubnetIds
      - !Ref AWS::NoValue

Resources:

  DBStream:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./async/database_event
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaDynamoDBExecutionRole
        - AmazonESFullAccess
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonKinesisFirehoseFullAccess
      Handler: database_event_handler.handle_db_event
      Timeout: 900
      Events:
        DBStreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !Ref dbStreamArn
            StartingPosition: LATEST
            BatchSize: 5
            MaximumBatchingWindowInSeconds: 5
            Enabled: true
