AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Data Pipeline Stack

Parameters:
  stage:
    Description: "Stage"
    Type: String
  backupRegion:
    Description: "Backup Region"
    Type: String
  stackType:
    Description: "(primary|secondary)"
    Type: String
    AllowedValues:
      - 'primary'
      - 'secondary'
    Default: 'primary'
  appId:
    Description: "App ID used for unique s3 bucket names (no special characters, all lowercase)"
    Type: String
    Default: "t52x7zk6ls6p"
  enableS3Replication:
    Description: "Is s3 replication enabled (true|false) NOTE: buckets must exist"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  enableBackup:
    Description: "Is aws backup enabled (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'


Conditions:
  isPrimary: !Equals [ !Ref stackType, 'primary' ]
  isS3ReplicationEnabled: !Equals [ !Ref enableS3Replication, 'true' ]
  isBackupEnabled: !Equals [ !Ref enableBackup, 'true' ]
  isPrimaryAndBackupEnabled: !And
    - !Condition isPrimary
    - !Condition isBackupEnabled

Resources:

  S3ReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 's3.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'PrimaryAccessLogS3ReplicationPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 's3:GetReplicationConfiguration'
                  - 's3:ListBucket'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 's3:GetObjectVersion'
                  - 's3:GetObjectVersionAcl'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 's3:ReplicateObject'
                  - 's3:ReplicateDelete'
                  - 's3:ObjectOwnerOverrideToBucketOwner'
                Effect: Allow
                Resource: '*'

  DataPipelineDestinationS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${appId}-${stage}-${stackType}-data-pipeline-destination"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: 'alias/aws/s3'
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Sub "${appId}-${stage}-${stackType}-access-log-bucket"
        LogFilePrefix: 'data-pipeline-access-logs/'
#      ReplicationConfiguration: !If
#        - isS3ReplicationEnabled
#        - Role: !GetAtt S3ReplicationRole.Arn
#          Rules:
#            - Id: 'ReplicationRule'
#              Status: Enabled
#              Destination:
#                Bucket: !If [ isPrimary, !Sub "arn:aws:s3:::${appId}-${stage}-secondary-data-pipeline-destination", !Sub "arn:aws:s3:::${appId}-${stage}-primary-data-pipeline-destination" ]
#                StorageClass: STANDARD
#              Prefix: ''
#        - !Ref AWS::NoValue

  FirehoseDeliveryRole:
    Condition: isPrimary
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: MyFirehoseDeliveryPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                Resource:
                  - !Sub "arn:aws:s3:::${DataPipelineDestinationS3Bucket}"
                  - !Sub "arn:aws:s3:::${DataPipelineDestinationS3Bucket}/*"

  FirehoseDeliveryStream:
    Condition: isPrimary
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt DataPipelineDestinationS3Bucket.Arn
        RoleARN: !GetAtt FirehoseDeliveryRole.Arn
        Prefix: "db/"
        ErrorOutputPrefix: "error/"
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CompressionFormat: "UNCOMPRESSED"
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseDeliveryStreamS3LogGroup
          LogStreamName: 'FirehoseDeliveryStreamS3LogStream'
        EncryptionConfiguration:
          KMSEncryptionConfig:
            AWSKMSKeyARN: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"

  FirehoseDeliveryStreamS3LogGroup:
    Condition: isPrimary
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain

  FirehoseDeliveryStreamS3LogStream:
    Condition: isPrimary
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseDeliveryStreamS3LogGroup
      LogStreamName: 'FirehoseDeliveryStreamS3LogStream'

  FirehoseDeliveryStreamParameter:
    Condition: isPrimary
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "FIREHOSE_DELIVERY_STREAM"
      Type: "String"
      Value: !Ref FirehoseDeliveryStream

Outputs:
  DataPipelineDestinationS3BucketName:
    Value: !Ref DataPipelineDestinationS3Bucket
    Description: "The name of the Amazon S3 bucket."
