AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  User API Stack

Globals:
  Api:
    Auth:
      DefaultAuthorizer: "PUBLIC"
  Function:
    MemorySize: 256
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        "stage": !Ref "stage"
        "region": !Ref AWS::Region
        "DB_TABLE": !Sub '${dbTableName}-${stage}'
        "BACKUP_REGION": !Ref backupRegion
        "VPC_ENABLED": !Ref enableVPC
        "CORS_ALLOWED_ORIGINS": !Ref corsAllowedOrigins
    Layers:
      - !Ref coreLayer
      - !Ref apiLayer
    VpcConfig: !If
      - isVPCEnabled
      - SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds: !Ref vpcSubnetIds
      - !Ref AWS::NoValue

Parameters:
  stage:
    Description: "Stage"
    Type: String
  backupRegion:
    Description: "Backup Region"
    Type: String
  coreLayer:
    Description: "Core Library Layer"
    Type: String
  apiLayer:
    Description: "API Library Layer"
    Type: String
  securityGroup:
    Description: "Lambda VPC security group"
    Type: String
    Default: ""
  vpcSubnetIds:
    Description: "Lambda VPC Subnets"
    Type: CommaDelimitedList
    Default: ""
  enableVPC:
    Description: "Is VPC enabled (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  dbTableName:
    Description: "Table Name"
    Type: String
    Default: "DBTable"
  corsAllowedOrigins:
    Description: "CORS ALLOWED ORIGINS (response header: Access-Control-Allow-Origin)"
    Type: String
    Default: ''

Conditions:
  isVPCEnabled: !Equals [ !Ref enableVPC, 'true' ]

Resources:

  CloudWatchRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'

  ApiCWLRoleArn:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  ApiGatewayApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayApiAccessLogGroup.Arn
        Format: '{
          "accountId": "$context.accountId",
          "apiId": "$context.apiId",
          "awsEndpointRequestId": "$context.awsEndpointRequestId",
          "domainName": "$context.domainName",
          "domainPrefix": "$context.domainPrefix",
          "errorMessage": "$context.error.message",
          "errorMessageString": "$context.error.messageString",
          "errorResponseType": "$context.error.responseType",
          "errorValidationErrorString": "$context.error.validationErrorString",
          "extendedRequestId": "$context.extendedRequestId",
          "httpMethod": "$context.httpMethod",
          "identitySourceIp": "$context.identity.sourceIp",
          "identityUserAgent": "$context.identity.userAgent",
          "path": "$context.path",
          "protocol": "$context.protocol",
          "requestId": "$context.requestId",
          "requestTime": "$context.requestTime",
          "resourceId": "$context.resourceId",
          "resourcePath": "$context.resourcePath",
          "stage": "$context.stage",
          "wafResponseCode": "$context.wafResponseCode",
          "webaclArn": "$context.webaclArn"
        }'
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /v1.0/user:
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${QueryUserFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          /v1.0/user/{id}:
            get:
              parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    maxLength: 36
                    minLength: 36
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
            patch:
              parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    maxLength: 36
                    minLength: 36
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        status:
                          type: string
                      required:
                        - status
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateUserFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
            delete:
              parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    maxLength: 36
                    minLength: 36
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteUserFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          /v1.0/user/{id}/associate:
            put:
              parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    maxLength: 36
                    minLength: 36
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AssociateUserFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          components:
            requestValidators:
              ValidateBodyAndParams:
                validateRequestBody: true
                validateRequestParameters: true

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub '${stage} USER APIGW'
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - HEAD
            - GET
          Compress: true
          DefaultTTL: 0
          ForwardedValues:
            Headers:
              - Authorization
              - User-Agent
            QueryString: true
          TargetOriginId: apigwOrigin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName: !Sub '${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com'
            Id: apigwOrigin
        PriceClass: PriceClass_100

  QueryUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/
      Handler: user_controller.query
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/user
            Method: get

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/
      Handler: user_controller.get
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/user/{id}
            Method: get

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/
      Handler: user_controller.update
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/user/{id}
            Method: patch

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/
      Handler: user_controller.delete
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/user/{id}
            Method: delete

  AssociateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user/
      Handler: user_controller.associate
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/user/{id}/associate
            Method: put

Outputs:
  UserApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  UserApiCloudFrontDistributionUrl:
    Value: !Join [ '', [ 'https://', !GetAtt [ CloudFrontDistribution, DomainName ] ] ]
    Description: URL of the CloudFront distribution
  GetUserFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt GetUserFunction.Arn
  GetUserFunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt GetUserFunctionRole.Arn
