AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Open Search Stack

Parameters:
  stage:
    Description: "Stage"
    Type: String
  backupRegion:
    Description: "Backup Region"
    Type: String
  coreLayer:
    Description: "Core Library Layer"
    Type: String
  apiLayer:
    Description: "API Library Layer"
    Type: String
  stackType:
    Description: "(primary|secondary)"
    Type: String
    AllowedValues:
      - 'primary'
      - 'secondary'
    Default: 'primary'
  dbStreamArn:
    Description: "DB Stream ARN"
    Type: String
  dbTableName:
    Description: "Table Name"
    Type: String
    Default: "DBTable"

Conditions:
  isPrimary: !Equals [ !Ref stackType, 'primary' ]

Resources:

  DBEventStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: isPrimary
    Properties:
      TemplateURL: template.db.event.yaml
      Parameters:
        stage: !Ref stage
        backupRegion: !Ref backupRegion
        coreLayer: !Ref coreLayer
        enableVPC: false
        dbStreamArn: !Ref dbStreamArn

  QueueStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: template.queue.yaml
      Parameters:
        stage: !Ref stage
        backupRegion: !Ref backupRegion
        coreLayer: !Ref coreLayer
        enableVPC: false

  AuthApiStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: template.api.auth.yaml
      Parameters:
        stage: !Ref stage
        backupRegion: !Ref backupRegion
        coreLayer: !Ref coreLayer
        apiLayer: !Ref apiLayer
        enableVPC: false
        dbTableName: !Ref dbTableName
        accessLogQueueUrl: !GetAtt QueueStack.Outputs.AccessLogQueueUrl
        errorLogQueueUrl: !GetAtt QueueStack.Outputs.ErrorLogQueueUrl

  UserApiStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: template.api.user.yaml
      Parameters:
        stage: !Ref stage
        backupRegion: !Ref backupRegion
        coreLayer: !Ref coreLayer
        apiLayer: !Ref apiLayer
        enableVPC: false
        dbTableName: !Ref dbTableName
        accessLogQueueUrl: !GetAtt QueueStack.Outputs.AccessLogQueueUrl
        errorLogQueueUrl: !GetAtt QueueStack.Outputs.ErrorLogQueueUrl
