AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Auth Event Stack

Parameters:
  stage:
    Description: "Stage"
    Type: String
  backupRegion:
    Description: "Backup Region"
    Type: String
  coreLayer:
    Description: "Core Library Layer"
    Type: String
  securityGroup:
    Description: "Lambda VPC security group"
    Type: String
    Default: ""
  vpcSubnetIds:
    Description: "Lambda VPC Subnets"
    Type: CommaDelimitedList
    Default: ""
  enableVPC:
    Description: "Is VPC enabled (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'

Conditions:
  isVPCEnabled: !Equals [ !Ref enableVPC, 'true' ]

Globals:
  Function:
    MemorySize: 256
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        "stage": !Ref "stage"
        "region": !Ref AWS::Region
    Layers:
      - !Ref coreLayer
    VpcConfig: !If
      - isVPCEnabled
      - SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds: !Ref vpcSubnetIds
      - !Ref AWS::NoValue

Resources:

  AuthEventQueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./async/auth_event
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AmazonSQSFullAccess
        - SQSPollerPolicy:
            QueueName: !GetAtt AuthEventQueue.QueueName
      Handler: auth_event_handler.handle_auth_event
      Events:
        ErrorLogEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AuthEventQueue.Arn
            BatchSize: 10

  AuthEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  AuthEventQueueUrlParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub 'AUTH_EVENT_QUEUE_URL-${stage}'
      Type: "String"
      Value: !GetAtt AuthEventQueue.QueueUrl

Outputs:
  AuthEventQueueName:
    Value: !GetAtt AuthEventQueue.QueueName
  AuthEventQueueUrl:
    Value: !GetAtt AuthEventQueue.QueueUrl
