AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Auth API Stack

Globals:
  Api:
    Auth:
      DefaultAuthorizer: "PUBLIC"
  Function:
    MemorySize: 256
    Timeout: 30
    Runtime: python3.9
    Tracing: Active
    Environment:
      Variables:
        "stage": !Ref "stage"
        "region": !Ref AWS::Region
        "REPLICA_REGION": !Ref replicaRegion
        "VPC_ENABLED": !Ref enableVPC
        "CORS_ALLOWED_ORIGINS": !Sub "${corsAllowedOrigins}"
    Layers:
      - !Ref coreLayer
      - !Ref apiLayer
    VpcConfig: !If
      - isVPCEnabled
      - SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds: !Ref vpcSubnetIds
      - !Ref AWS::NoValue


Parameters:
  stage:
    Description: "Stage"
    Type: String
  replicaRegion:
    Description: "Replica Region"
    Type: String
  coreLayer:
    Description: "Core Library Layer"
    Type: String
  apiLayer:
    Description: "API Library Layer"
    Type: String
  securityGroup:
    Description: "Lambda VPC security group"
    Type: String
    Default: ""
  vpcSubnetIds:
    Description: "Lambda VPC Subnets"
    Type: CommaDelimitedList
    Default: ""
  enableVPC:
    Description: "Is VPC enabled (true|false)"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  dbTableName:
    Description: "Table Name"
    Type: String
    Default: "DBTable"
  corsAllowedOrigins:
    Description: "CORS ALLOWED ORIGINS (response header: Access-Control-Allow-Origin)"
    Type: String
    Default: ''
  enableApiCDN:
    Description: "Is CDN for APIGW enabled"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  enableDNS:
    Description: "Is Route53 DNS enabled"
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  hostedZoneName:
    Description: "DNS Hosted Zone"
    Type: String
    Default: ''
  hostedZoneId:
    Description: "DNS Hosted Id"
    Type: String
    Default: ''


Conditions:
  isVPCEnabled: !Equals [ !Ref enableVPC, 'true' ]
  isApiCDNEnabled: !Equals [ !Ref enableApiCDN, 'true' ]
  isDNSEnabled: !Equals [ !Ref enableDNS, 'true' ]

Resources:

  CloudWatchRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'

  ApiCWLRoleArn:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  ApiGatewayApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain

  AcmCertificate:
    Condition: isDNSEnabled
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${hostedZoneName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref hostedZoneName
          HostedZoneId: !Ref hostedZoneId

  CustomDomain:
    Condition: isDNSEnabled
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub "api-auth-${stage}.${hostedZoneName}"
      RegionalCertificateArn: !Ref AcmCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Condition: isDNSEnabled
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ApiGatewayApi
      Stage: 'Prod'

  HealthCheck:
    Condition: isDNSEnabled
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: /Prod/v1.0/health
        FullyQualifiedDomainName: !Sub "${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com"
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true
        Regions:
          - us-east-1
          - us-west-1
          - us-west-2
      HealthCheckTags:
        - Key: 'Name'
          Value: !Sub 'AuthApiHealthCheck-${AWS::Region}'

  HealthCheckStatusAlarm:
    Condition: isDNSEnabled
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Health check failed
      Namespace: AWS/Route53
      MetricName: HealthCheckStatus
      Dimensions:
        - Name: HealthCheckId
          Value: !Ref HealthCheck
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: missing
      AlarmActions:
        - !Ref HealthCheckSNSAlertTopic

  HealthCheckSNSAlertTopic:
    Condition: isDNSEnabled
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Route53HealthCheckAlert
      Subscription:
        - Protocol: email
          Endpoint: ianballard.dev@gmail.com

  ARecordSet:
    Condition: isDNSEnabled
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref hostedZoneId
      Name: !Sub "api-auth-${stage}.${hostedZoneName}"
      Type: A
      SetIdentifier: !Sub "auth-${stage}-${AWS::Region}"
      Region: !Ref AWS::Region
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: true
      HealthCheckId: !Ref HealthCheck

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: "Auth API"
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayApiAccessLogGroup.Arn
        Format: '{
          "accountId": "$context.accountId",
          "apiId": "$context.apiId",
          "awsEndpointRequestId": "$context.awsEndpointRequestId",
          "domainName": "$context.domainName",
          "domainPrefix": "$context.domainPrefix",
          "errorMessage": "$context.error.message",
          "errorMessageString": "$context.error.messageString",
          "errorResponseType": "$context.error.responseType",
          "errorValidationErrorString": "$context.error.validationErrorString",
          "extendedRequestId": "$context.extendedRequestId",
          "httpMethod": "$context.httpMethod",
          "identitySourceIp": "$context.identity.sourceIp",
          "identityUserAgent": "$context.identity.userAgent",
          "path": "$context.path",
          "protocol": "$context.protocol",
          "requestId": "$context.requestId",
          "requestTime": "$context.requestTime",
          "resourceId": "$context.resourceId",
          "resourcePath": "$context.resourcePath",
          "stage": "$context.stage",
          "wafResponseCode": "$context.wafResponseCode",
          "webaclArn": "$context.webaclArn"
        }'
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /v1.0/health:
            options:
              responses:
                "200":
                  description: "CORS"
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: !Sub "'${corsAllowedOrigins}'"
            get:
              responses:
                '200':
                  description: Successful health check
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          /v1.0/signup:
            options:
              responses:
                "200":
                  description: "CORS"
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: !Sub "'${corsAllowedOrigins}'"
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        username:
                          type: string
                          minLength: 4
                        password:
                          type: string
                          minLength: 8
                        email:
                          type: string
                          minLength: 3
                        first_name:
                          type: string
                          minLength: 1
                        last_name:
                          type: string
                          minLength: 1
                      required:
                        - username
                        - password
                        - email
                        - first_name
                        - last_name
              responses:
                '201':
                  description: Successful signup
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          username:
                            type: string
                          profile:
                            type: string
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignUpFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          /v1.0/confirm_sign_up:
            options:
              responses:
                "200":
                  description: "CORS"
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: !Sub "'${corsAllowedOrigins}'"
            get:
              responses:
                '200':
                  description: Successful confirmation
              parameters:
                - name: username
                  in: query
                  required: true
                  schema:
                    type: string
                    minLength: 4
                - name: code
                  in: query
                  required: true
                  schema:
                    type: string
                    minLength: 6
                    maxLength: 6
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmSignUpFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
          /v1.0/auth:
            options:
              responses:
                "200":
                  description: "CORS"
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: !Sub "'${corsAllowedOrigins}'"
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        username:
                          type: string
                          minLength: 4
                        password:
                          type: string
                          minLength: 8
                      required:
                        - username
                        - password
              responses:
                '200':
                  description: Successful authentication
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          ChallengeParameters:
                            type: object
                          AuthenticationResult:
                            type: object
                            properties:
                              AccessToken:
                                type: string
                              ExpiresIn:
                                type: integer
                              TokenType:
                                type: string
                              RefreshToken:
                                type: string
                              IdToken:
                                type: string
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthenticateFunction.Arn}/invocations
              x-amazon-apigateway-request-validator: ValidateBodyAndParams
        components:
          requestValidators:
            ValidateBodyAndParams:
              validateRequestBody: true
              validateRequestParameters: true

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/auth/
      Handler: auth_controller.health
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AWSXRayDaemonWriteAccess
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/health
            Method: get

  # TODO update policies
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/auth/
      Handler: auth_controller.signup
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
        - AWSXRayDaemonWriteAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/signup
            Method: post

  # TODO update policies
  AuthenticateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/auth/
      Handler: auth_controller.authenticate
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AmazonSQSFullAccess
        - AWSXRayDaemonWriteAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/auth
            Method: post

  ConfirmSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/auth/
      Handler: auth_controller.confirm_sign_up
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonCognitoPowerUser
        - AmazonSQSFullAccess
        - AWSXRayDaemonWriteAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /v1.0/confirm_sign_up
            Method: get

Outputs:
  ApiId:
    Description: "API Gateway Id"
    Value: !Ref ApiGatewayApi
  SignUpFunctionArn:
    Description: "Sign Up Function ARN"
    Value: !GetAtt SignUpFunction.Arn
  SignUpFunctionIamRole:
    Description: "Implicit IAM Role created for the sign up function"
    Value: !GetAtt SignUpFunctionRole.Arn
  AuthenticateFunctionArn:
    Description: "Auth Function ARN"
    Value: !GetAtt AuthenticateFunction.Arn
  AuthenticateFunctionIamRole:
    Description: "Implicit IAM Role created for the auth function"
    Value: !GetAtt AuthenticateFunctionRole.Arn
  ApiGatewayUrl:
    Description: "API Url"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  ApiDomain:
    Description: "API Domain"
    Value: !Sub "${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com"

