name: Run unit tests
on: [push]
jobs:
  Run-unit-tests:
    name: Run the units tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run Unit Tests
        run: |
          python -m pytest tests/unit -v