name: Run Static Code Analysis

on: [push]

jobs:
  Static Code Analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Snyk scan
      uses: snyk/actions/python@0.3.0
      with:
        args: --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
